version: 0.1
phases:
  install:
    commands:
      - npm install serverless -g
      - npm install
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - serverless deploy --stage ${stage} --region ${region}
artifacts:
  files:
    - .serverless/**